---
title: "GroupGAssignment2B"
author: "Simone Albuquerque"
date: "2/22/2021"
output: html_document
---

```{r Load Packages}
library(tidyverse)
library(ggplot2)
```
```{r load function and create results table}
#call in auto power function
source("auto_power.R")

#generate samples from distribution 
nsample = 100
speeds = rnorm(mean = 25, sd = 4, n=nsample)
```


```{r results if speed changes and car mass and area is constant}
#create dataframe to store results

results = data.frame(speed = speeds, power = NA)

head(results)

#create column with results
#simple since only one variable, V is changing
results$power = auto_pwr(V=speeds, A=25, m=20000)

#visualize in graph 

ggplot(results, aes(speed, power/1000))+
  geom_point()+
  labs(x = "speed m/s", y = "power kW")

ggplot(results, aes(x = "Across Speed", y = power/1000))+ geom_boxplot()+ labs( y = "power kW")


```

```{r Create Inputs Possible Cars with mean speed}
# create df there are multiple cars with unique mass and areas

#car A mass = 20000kg, area 22m^2^
#car B mass = 65000 kg, area 30m^2^
#car C mass 38000 kg, area 22m^2^
# car D mass = 30000 kg, area - 10 m^2^


#mean highway speed = 100 km/hr ***convert to km/s***
speed_base = 100*.28
#since we want only 1 variable to change in this example

#generate inputs dataframe
possible_cars = data.frame(name = c("A", "B", "C", "D"),mass =  c(10000, 65000, 38000,30000), area = c(22, 30, 22, 10))

head(possible_cars)

#generate results dataframe
possible_cars$power = auto_pwr(V = speed_base, A = possible_cars$area, m = possible_cars$mass)


#visualize in graph
ggplot(possible_cars, aes(x = mass, y = power, fill = as.factor(area)))+
  geom_col()+
  labs(y = "Power W", x = "Mass (kg)")

```

```{r Random Sample of 100 highways with different conditions}
#Random Sample of 100 highways with different rolling coefficients; sample the rolling coefficients from a uniform distribution with a minimum value of 0.01 and a max value of 0.03

nsample = 100
r_coeff = runif(nsample, min = 0.01, max = 0.03)
plot(density(r_coeff), ylab="Distribution of Rolling Coefficients ")

```

```{r Use a for loop to compute the power for each highway for each car  speed = 120 km/hr (mean)}
#create a dataframe for results
power_for = as.data.frame(matrix(nrow=length(r_coeff), ncol=nrow(possible_cars)))
# because we don't initialize it - values are NA
head(power_for)

#convert mean velocity from km/h to m/s
V <- (120/3.6)

#run for all variables through a for loop 
for (i in 1:nrow(possible_cars)) {
  power_for[,i] = auto_pwr(A=possible_cars$area[i], m=possible_cars$mass[i], V = V, crolling = r_coeff)
}

# now it looks like above
head(power_for)

# we can add column names
colnames(power_for)=possible_cars$name

head(power_for)
```


```{r Use a for loop to compute the power for each highway for each car  speed = 120 km/hr (mean)}
# create a box plot
power_for_df<- power_for %>% 
  pivot_longer(cols = everything(), names_to = "name", values_to = "power" )

head(power_for_df)

power_for_plot<- ggplot(data = power_for_df, aes(x = name, y = power))+
                          geom_boxplot()

power_for_plot
```

```{r pmap  repeat calculations and create a second boxplot}
#run for all values of rolling coefficients
power_pmap = pmap(list(A = possible_cars$area, m=possible_cars$mass), auto_pwr, V=V, crolling = r_coeff)

#as a dataframe
power_pmap = as.data.frame(power_pmap, col.names=possible_cars$name) %>% 
  pivot_longer(cols = everything(), names_to = "name", values_to = "power")
  
#getting error can't run with name as a character and power as a double, but is running pivot_longer

head(power_pmap)
```


```{r pmap  boxplot}

pmap_box_plot = ggplot(power_pmap, aes(name,power, fill=name))+
  geom_boxplot()+
  ggtitle("pmap")

pmap_box_plot

```

